entry: gh-start
executions:
  - src:
      node: gh-checkout
      port: exec
    dst:
      node: run-v1-raspberry-kiwi-grape
      port: exec
  - src:
      node: gh-start
      port: exec-on-workflow_dispatch
    dst:
      node: gh-checkout
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 100
      y: 100
    settings:
      folded: false
  - id: gh-checkout
    type: github.com/actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    position:
      x: 410
      y: 120
    settings:
      folded: false
  - id: run-v1-raspberry-kiwi-grape
    type: run@v1
    position:
      x: 830
      y: 120
    inputs:
      script: echo "Hello World!"
    settings:
      folded: false
registries: []
description: ''
